# Kill all the statues in the map

kill @e[type=statue:babbon]
kill @e[type=statue:buffalo]
kill @e[type=statue:camel]
kill @e[type=statue:crocodile]
kill @e[type=statue:elephant]
kill @e[type=statue:fennec]
kill @e[type=statue:gazelle]
kill @e[type=statue:giraffe]
kill @e[type=statue:hippopotamus]
kill @e[type=statue:hyena]
kill @e[type=statue:jaburi]
kill @e[type=statue:jackal]
kill @e[type=statue:lion_female]
kill @e[type=statue:lion_male]
kill @e[type=statue:meerkat]
kill @e[type=statue:ostrich]
kill @e[type=statue:pangolin]
kill @e[type=statue:piranha]
kill @e[type=statue:porcupine]
kill @e[type=statue:rhinoceros]
kill @e[type=statue:serval]
kill @e[type=statue:snake]
kill @e[type=statue:vulture]
kill @e[type=statue:warthog]
kill @e[type=statue:zebra]
