execute @e[type=armor_stand,name=current,scores={ener=0..5}] ~ ~ ~ function gameplay/energy_tank/set/set_0
execute @e[type=armor_stand,name=current,scores={ener=6..17}] ~ ~ ~ function gameplay/energy_tank/set/set_1
execute @e[type=armor_stand,name=current,scores={ener=18..29}] ~ ~ ~ function gameplay/energy_tank/set/set_2
execute @e[type=armor_stand,name=current,scores={ener=30..41}] ~ ~ ~ function gameplay/energy_tank/set/set_3
execute @e[type=armor_stand,name=current,scores={ener=42..53}] ~ ~ ~ function gameplay/energy_tank/set/set_4
execute @e[type=armor_stand,name=current,scores={ener=54..65}] ~ ~ ~ function gameplay/energy_tank/set/set_5
execute @e[type=armor_stand,name=current,scores={ener=66..77}] ~ ~ ~ function gameplay/energy_tank/set/set_6
execute @e[type=armor_stand,name=current,scores={ener=78..89}] ~ ~ ~ function gameplay/energy_tank/set/set_7
execute @e[type=armor_stand,name=current,scores={ener=90..101}] ~ ~ ~ function gameplay/energy_tank/set/set_8
execute @e[type=armor_stand,name=current,scores={ener=102..115}] ~ ~ ~ function gameplay/energy_tank/set/set_9
execute @e[type=armor_stand,name=current,scores={ener=114..120}] ~ ~ ~ function gameplay/energy_tank/set/set_10