execute @e[type=armor_stand,name=current,scores={ener=0..3}] ~ ~ ~ function gameplay/energy_tank/set/set_0
execute @e[type=armor_stand,name=current,scores={ener=4..12}] ~ ~ ~ function gameplay/energy_tank/set/set_1
execute @e[type=armor_stand,name=current,scores={ener=13..21}] ~ ~ ~ function gameplay/energy_tank/set/set_2
execute @e[type=armor_stand,name=current,scores={ener=22..30}] ~ ~ ~ function gameplay/energy_tank/set/set_3
execute @e[type=armor_stand,name=current,scores={ener=31..39}] ~ ~ ~ function gameplay/energy_tank/set/set_4
execute @e[type=armor_stand,name=current,scores={ener=40..48}] ~ ~ ~ function gameplay/energy_tank/set/set_5
execute @e[type=armor_stand,name=current,scores={ener=49..57}] ~ ~ ~ function gameplay/energy_tank/set/set_6
execute @e[type=armor_stand,name=current,scores={ener=58..66}] ~ ~ ~ function gameplay/energy_tank/set/set_7
execute @e[type=armor_stand,name=current,scores={ener=67..75}] ~ ~ ~ function gameplay/energy_tank/set/set_8
execute @e[type=armor_stand,name=current,scores={ener=76..84}] ~ ~ ~ function gameplay/energy_tank/set/set_9
execute @e[type=armor_stand,name=current,scores={ener=85..90}] ~ ~ ~ function gameplay/energy_tank/set/set_10