execute @e[type=armor_stand,name=current,scores={ener=0..2}] ~ ~ ~ function gameplay/energy_tank/set/set_0
execute @e[type=armor_stand,name=current,scores={ener=3..8}] ~ ~ ~ function gameplay/energy_tank/set/set_1
execute @e[type=armor_stand,name=current,scores={ener=9..14}] ~ ~ ~ function gameplay/energy_tank/set/set_2
execute @e[type=armor_stand,name=current,scores={ener=15..20}] ~ ~ ~ function gameplay/energy_tank/set/set_3
execute @e[type=armor_stand,name=current,scores={ener=21..26}] ~ ~ ~ function gameplay/energy_tank/set/set_4
execute @e[type=armor_stand,name=current,scores={ener=27..32}] ~ ~ ~ function gameplay/energy_tank/set/set_5
execute @e[type=armor_stand,name=current,scores={ener=33..28}] ~ ~ ~ function gameplay/energy_tank/set/set_6
execute @e[type=armor_stand,name=current,scores={ener=39..44}] ~ ~ ~ function gameplay/energy_tank/set/set_7
execute @e[type=armor_stand,name=current,scores={ener=45..50}] ~ ~ ~ function gameplay/energy_tank/set/set_8
execute @e[type=armor_stand,name=current,scores={ener=51..56}] ~ ~ ~ function gameplay/energy_tank/set/set_9
execute @e[type=armor_stand,name=current,scores={ener=57..60}] ~ ~ ~ function gameplay/energy_tank/set/set_10